# {{ ansible_managed }}

# Use the base qbittorrent image
FROM lscr.io/linuxserver/qbittorrent:latest

# Install required packages
RUN apk upgrade
RUN apk add --no-cache wireguard-tools iptables

# Expose required ports
EXPOSE 51820/udp

# Install vuetorrent UI
RUN curl -fsSL "https://github.com/vuetorrent/vuetorrent/releases/latest/download/vuetorrent.zip" > "/tmp/vuetorrent.zip" && \
    unzip "/tmp/vuetorrent.zip" -d / && \
    rm "/tmp/vuetorrent.zip" && \
    chmod -R u=rwX,go=rX "/vuetorrent"

# Copy the S6-overlay and WireGuard configuration files
COPY /root /
RUN chmod 600 /etc/wireguard/wg0.conf
