---
- name: Install linux headers
  become: true
  ansible.builtin.apt:
    name:
      - "linux-headers-{{ ansible_kernel }}"
    state: present

- name: Install ZFS
  become: true
  ansible.builtin.apt:
    name:
      - zfsutils-linux
    default_release: "{{ ansible_distribution_release }}-backports"
    state: present

- name: Copy ZFS auto key loading service file
  become: true
  ansible.builtin.template:
    src: zfs-load-key.service.j2
    dest: /etc/systemd/system/zfs-load-key.service
    mode: "0644"

- name: Enable and start ZFS mount services and Load keys service
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    masked: false
  with_items:
    - zfs.target
    - zfs-load-key.service
