---
- name: Create mealie infrastructure root folders
  become: true
  ansible.builtin.file:
    path: "{{ mealie_infra }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"

- name: Create all docker related mealie infrastructure folders
  ansible.builtin.file:
    path: "{{ mealie_infra }}/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "../templates"
  when:
    - item.state == 'directory'

- name: Copy all docker related mealie infrastructure files
  ansible.builtin.template:
    src: "{{ item.path }}"
    dest: "{{ mealie_infra }}/{{ item.path | replace('.j2', '') }}"
    mode: "0644"
  with_community.general.filetree: "../templates"
  when:
    - item.state == 'file'
    - "'Caddyfile' not in item.path"

- name: Copy Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ caddy_caddyfiles_folder }}/{{ role_name }}"
    mode: "0644"
  notify: Restart Caddy

- name: Start the mealie services
  community.docker.docker_compose_v2:
    project_src: "{{ mealie_infra }}"
    remove_orphans: true
