---
- name: Restart amdfan service
  become: true
  ansible.builtin.service:
    name: amdfan
    state: restarted

- name: Restart amdgpu-clocks service
  become: true
  ansible.builtin.service:
    name: amdgpu-clocks
    state: restarted
