---
- name: Fetch fisher installer script
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish
    return_content: true
  register: fisher_installer

- name: Install fisher module
  ansible.builtin.shell:
    cmd: source -- && fisher install jorgebucaran/fisher
    stdin: "{{ fisher_installer.content }}"
    executable: /usr/bin/fish
  register: fisher_installed
  changed_when: fisher_installed.rc != 0

- name: Install fish modules # noqa: no-changed-when Configuring this also updates the modules
  ansible.builtin.shell: fisher install {{ item }}
  args:
    executable: /usr/bin/fish
  with_items: "{{ fish_modules }}"
