---
- name: Install fish packages
  become: true
  ansible.builtin.apt:
    name:
      - fish
    state: present

- name: Create all fish related folders
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/fish/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "../templates"
  when: item.state == 'directory'

- name: Copy fish user config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ xdg_config_home }}/fish/{{ item.path | replace('.j2', '') }}"
    mode: "0644"
  with_community.general.filetree: "../templates"
  when: item.state == 'file'

- name: Change the current user shell to fish
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish

- name: Fetch starship
  ansible.builtin.uri:
    url: https://starship.rs/install.sh
    return_content: true
  register: starship_installer

- name: Run starship installer
  ansible.builtin.command:
    cmd: sh -s -- -y
    stdin: "{{ starship_installer.content }}"
  register: starship_installed
  changed_when: starship_installed.rc != 0
