---
- name: Find all files named Dockerfile in {{ docker_base_infra }}
  ansible.builtin.find:
    paths: "{{ docker_base_infra }}"
    recurse: true
    patterns: "*Dockerfile"
  register: dockerfiles

- name: Create diun infrastructure root folders
  become: true
  ansible.builtin.file:
    path: "{{ diun_infra }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"

- name: Create all docker related diun infrastructure folders
  ansible.builtin.file:
    path: "{{ diun_infra }}/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "../templates"
  when: item.state == 'directory'

- name: Copy all docker related diun infrastructure files
  ansible.builtin.template:
    src: "{{ item.path }}"
    dest: "{{ diun_infra }}/{{ item.path | replace('.j2', '') }}"
    mode: "0644"
  with_community.general.filetree: "../templates"
  when:
    - item.state == 'file'

- name: Start the diun services
  community.docker.docker_compose_v2:
    project_src: "{{ diun_infra }}"
    remove_orphans: true
