---
- name: Reboot
  become: true
  ansible.builtin.reboot:

- name: Restart smbd service
  become: true
  ansible.builtin.systemd:
    name: smbd
    state: restarted

- name: Add samba password to user # noqa: no-changed-when risky-shell-pipe
  become: true
  ansible.builtin.shell: printf "{{ samba.private.password }}\n{{ samba.private.password }}\n" | smbpasswd -s -a {{ samba.private.user }}
