---
- name: Reboot
  become: true
  ansible.builtin.reboot:

- name: Restart smbd service
  become: true
  ansible.builtin.systemd:
    name: smbd
    state: restarted

- name: Add samba password to user
  become: true
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      printf "{{ item.password }}\n{{ item.password }}\n" | smbpasswd -s -a {{ item.user }}
    executable: /bin/bash
  loop: "{{ samba_private_shares }}"
  register: samba_password_added
  changed_when: samba_password_added.rc != 0
