---
- name: Configure aspire
  hosts: aspire
  roles:
    - role: system
    - role: fish
    - { role: geerlingguy.security, become: true }
    - { role: chriswayg.msmtp-mailer, become: true }
    - role: autoupdate
    - role: dropbear
    - role: zfs
    - role: nfs
    - role: samba
    - role: docker
    - role: media_server
    - role: diun
    - role: caddy
