---
- name: Configure all hosts
  hosts: home
  roles:
    - role: common.system
    - role: common.fish

- name: Configure servers hosts
  hosts: servers
  roles:
    - { role: geerlingguy.security, become: true }
    - { role: chriswayg.msmtp-mailer, become: true }
    - role: debian.unatended-upgrades

- name: Configure aspire server
  hosts: aspire
  roles:
    - role: debian.dropbear
    - role: debian.samba
    - role: debian.nfs
    - role: debian.docker
    - role: common.media-server
    - role: watchtower
