---
- name: Configure all hosts
  hosts: home
  roles:
    - role: system
    - role: fish

- name: Configure all servers hosts
  hosts: servers
  roles:
    - { role: geerlingguy.security, become: true }
    - { role: chriswayg.msmtp-mailer, become: true }
    - role: unatended-upgrades

- name: Configure aspire host
  hosts: aspire
  roles:
    - role: dropbear
    - role: docker
    - role: media-server
    - role: watchtower
    - role: nfs
    - role: samba

- name: Configure opendan host
  hosts: opendan
  roles:
    - role: pacman
    - role: dotfiles
    - role: gpu-overclocking
    - role: sensors
    - role: automatic-shutdown
