---
- name: Configure everything
  hosts: home
  roles:
    - role: system
    - role: fish

- name: Configure servers
  hosts: servers
  roles:
    - { role: geerlingguy.security, become: true }
    - { role: chriswayg.msmtp-mailer, become: true }
    - role: unatended_upgrades

- name: Pi sbc server
  hosts: pi
  roles:
    - role: access

- name: Aspire laptop server
  hosts: aspire
  roles:
    - role: dropbear
    - role: zfs
    - role: samba
