---
- name: Configure all hosts
  hosts: home
  roles:
    - role: common.system
    - role: common.fish

- name: Configure all servers hosts
  hosts: servers
  roles:
    - { role: geerlingguy.security, become: true }
    - { role: chriswayg.msmtp-mailer, become: true }
    - role: debian.unatended-upgrades

- name: Configure aspire host
  hosts: aspire
  roles:
    - role: debian.dropbear
    - role: debian.samba
    - role: debian.nfs
    - role: debian.docker
    - role: common.media-server
    - role: common.watchtower

- name: Configure opendan host
  hosts: opendan
  roles:
    - role: arch.pacman
    - role: arch.dotfiles
