[tool.ruff]

line-length = 100
target-version = "py312"

[tool.ruff.lint]

select = ["ALL"]
ignore = [
    "D",      # pydostyle
    "T20",    # flake8-print trigger on every print or pprint
    "D203",   # one-blank-line-before-class
    "D213",   # multi-line-summary-second-line
    "ISC001", # Implicitly concatenated string literals on one line - Conflicts with formatter
    "COM812", # Trailing comma missing - Conflicts with formatter
]
