---
- name: Install fish shell
  become: true
  ansible.builtin.apt:
    name:
      - fish
    state: present

- name: Fetch fisher installer script
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish
    return_content: true
  register: fisher_installer

- name: Install fisher module
  ansible.builtin.shell:
    cmd: source -- && fisher install jorgebucaran/fisher
    stdin: "{{ fisher_installer.content }}"
    executable: /usr/bin/fish
  register: fisher_installed
  changed_when: fisher_installed.rc != 0

- name: Fetch starship installer script
  ansible.builtin.uri:
    url: https://starship.rs/install.sh
    return_content: true
  register: starship_installer

- name: Install starship prompt
  become: true
  ansible.builtin.command:
    cmd: sh -s -- -y
    stdin: "{{ starship_installer.content }}"
  register: starship_installed
  changed_when: starship_installed.rc != 0
