---
- name: Create caddy infrastructure root folders
  become: true
  ansible.builtin.file:
    path: "{{ caddy_infra }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"

- name: Create all docker related caddy infrastructure folders
  ansible.builtin.file:
    path: "{{ caddy_infra }}/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "../templates"
  when: item.state == 'directory'

- name: Copy all docker related caddy infrastructure files
  ansible.builtin.template:
    src: "{{ item.path }}"
    dest: "{{ caddy_infra }}/{{ item.path | replace('.j2', '') }}"
    mode: "0644"
  with_community.general.filetree: "../templates"
  when:
    - item.state == 'file'

- name: Start the caddy services
  community.docker.docker_compose_v2:
    project_src: "{{ caddy_infra }}"
    remove_orphans: true
