---
- name: Install Samba
  become: true
  ansible.builtin.apt:
    name:
      - samba
    state: present

- name: Add a user for private share
  become: true
  ansible.builtin.user:
    name: "{{ item.user }}"
  loop: "{{ samba.private }}"
  notify:
    - Reboot
    - Add samba password to user

- name: Enable smbd service
  become: true
  ansible.builtin.systemd:
    name: smbd
    enabled: true

- name: Create samba folder for private share
  become: true
  ansible.builtin.file:
    path: "{{ item.share }}"
    state: directory
    mode: "0755"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
  loop: "{{ samba.private }}"

- name: Adding the configuration for the private share
  become: true
  ansible.builtin.blockinfile:
    marker: "# {mark} {{ item.name }} share"
    path: /etc/samba/smb.conf
    insertafter: EOF
    block: |
      [{{ item.name }}]
      path = {{ item.share }}
      valid users = {{ item.user }}
      public = no
      writeable = yes
    backup: true
    prepend_newline: true
  loop: "{{ samba.private }}"
  notify: Restart smbd service

- name: Allow all handlers to run
  ansible.builtin.meta: flush_handlers
