---
- name: Install Samba
  become: true
  ansible.builtin.apt:
    name:
      - samba
    state: present

- name: Add samba user
  become: true
  ansible.builtin.user:
    name: "{{ samba_user }}"
  notify:
    - Reboot
    - Add samba password to user

- name: Enable smbd service
  become: true
  ansible.builtin.systemd:
    name: smbd
    enabled: true

- name: Share ZFS pools over samba
  become: true
  community.general.zfs:
    name: "{{ item.name }}"
    state: present
    extra_zfs_properties: |
      sharesmb=on
  loop: "{{ samba_shares.zfs }}"
  when: samba_shares is defined and samba_shares.zfs | length > 0

- name: Create paths with proper access for all shares
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "0755"
    owner: "{{ samba_user }}"
    group: "{{ samba_user }}"
  loop: "{{ samba_shares.system + samba_shares.zfs }}"
  when: samba_shares is defined and (samba_shares.system | length > 0 or samba_shares.zfs | length > 0)

- name: Add system shares to samba conf
  become: true
  ansible.builtin.blockinfile:
    marker: "# {mark} {{ item.name }} share"
    path: /etc/samba/smb.conf
    insertafter: EOF
    block: |
      [{{ item.name }}]
      path = {{ item.path }}
      valid users = {{ samba_user }}
      public = no
      writeable = yes
    backup: true
    prepend_newline: true
  loop: "{{ samba_shares.system }}"
  notify: Restart smbd service
  when: samba_shares is defined and samba_shares.system | length > 0

- name: Allow all handlers to run
  ansible.builtin.meta: flush_handlers
