---
- name: Create immich infrastructure root folders
  become: true
  ansible.builtin.file:
    path: "{{ immich_infra }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"

- name: Create all docker related immich infrastructure folders
  ansible.builtin.file:
    path: "{{ immich_infra }}/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "../templates"
  when:
    - item.state == 'directory'

- name: Copy all docker related immich infrastructure files
  ansible.builtin.template:
    src: "{{ item.path }}"
    dest: "{{ immich_infra }}/{{ item.path | replace('.j2', '') }}"
    mode: "0644"
  with_community.general.filetree: "../templates"
  when:
    - item.state == 'file'
    - "'Caddyfile' not in item.path"

- name: Copy Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ caddy_caddyfiles_folder }}/{{ role_name }}"
    mode: "0644"
  notify: Restart Caddy

- name: Start the immich services
  community.docker.docker_compose_v2:
    project_src: "{{ immich_infra }}"
    remove_orphans: true
