---
- name: Update Arch Linux system fully
  kewlfft.aur.aur:
    upgrade: true
    update_cache: true

- name: Install firmware packages
  kewlfft.aur.aur:
    name: "{{ firmware_packages }}"
  when: firmware_packages is defined
