---
- name: Control LED on sbc
  become: true
  ansible.builtin.blockinfile:
    marker: "# {mark} Disable all LED"
    path: /boot/config.txt
    insertafter: EOF
    block: |
      #Disable Power LED (Red)
      dtparam=pwr_led_activelow=off
      #Disable Activity LED (Green)
      dtparam=act_led_trigger=none
      dtparam=act_led_activelow=off
      #Disable LAN LEDs
      dtparam=eth_led0=14
      dtparam=eth_led1=14
      #Disable bluetooth
      dtoverlay=disable-bt
  notify: Reboot
