---
- name: Check if system is running Archlinux
  ansible.builtin.fail:
    msg: The system is not running Archlinux!
  when: ansible_distribution != "Archlinux"

- name: Import reflector tasks
  ansible.builtin.import_tasks: reflector.yml

- name: Import aur-helper tasks
  ansible.builtin.import_tasks: aur-helper.yml

- name: Remove debug option in makepkg.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/makepkg.conf
    regexp: '(OPTIONS=\(.*) debug (.*\))'
    line: '\1 !debug \2'
    backrefs: true
