---
- name: Create joplin infrastructure root folders
  become: true
  ansible.builtin.file:
    path: "{{ joplin.infra }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"

- name: Create all docker related joplin infrastructure folders
  ansible.builtin.file:
    path: "{{ joplin.infra }}/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "../templates"
  when: item.state == 'directory'

- name: Copy all docker related joplin infrastructure files
  ansible.builtin.template:
    src: "{{ item.path }}"
    dest: "{{ joplin.infra }}/{{ item.path | replace('.j2', '') }}"
    mode: "0644"
  with_community.general.filetree: "../templates"
  when:
    - item.state == 'file'

- name: Create joplin data folders
  become: true
  ansible.builtin.file:
    path: "{{ joplin.data }}"
    state: directory
    mode: "0755"
    owner: 1001
    group: 1001

- name: Start the joplin services
  community.docker.docker_compose_v2:
    project_src: "{{ joplin.infra }}"
    remove_orphans: true
