---
- name: Enable Colour and ParallelDownload in pacman.conf
  become: true
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: ^#\s*{{ item }}
    replace: "{{ item }}"
  with_items:
    - Color
    - ParallelDownloads

- name: Set ParallelDownloads value in pacman.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: ^ParallelDownloads =
    line: "ParallelDownloads = {{ pacman.parallel_downloads }}"

- name: Install AUR helper
  kewlfft.aur.aur:
    name:
      - "{{ pacman.aur_helper }}-bin"
