---
- name: Install reflector
  kewlfft.aur.aur:
    name:
      - reflector

- name: Enable reflector timer
  become: true
  ansible.builtin.systemd:
    name: reflector.timer
    enabled: true

- name: Enable country selection
  become: true
  ansible.builtin.replace:
    path: /etc/xdg/reflector/reflector.conf
    regexp: ^#\s*--country
    replace: --country

- name: Set the country list
  become: true
  ansible.builtin.lineinfile:
    path: /etc/xdg/reflector/reflector.conf
    regexp: ^--country
    line: --country {{ pacman.countries | join(',') }}
