---
### Ansible

ansible_host: 192.168.1.253
ansible_user: acer
ansible_connection: ssh
ansible_port: 22
ansible_ssh_private_key_file: ~/.ssh/servers

### Host

host_name: aspire
host_firmware_packages:
  - firmware-iwlwifi
  - firmware-realtek
  # - bumblebee-nvidia
  # - primus-nvidia
  # - primus-vk-nvidia

### Dropbear

dropbear_gateway: 192.168.1.254
dropbear_netmask: 255.255.255.0
dropbear_ip: 192.168.1.252
dropbear_authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEf5Nt/JVAhptEaxDU/5Rdf284QswbVpKOOWFf7o5RAk"

### Network Sharing

_drives:
  zfs:
    data_vault:
      mountpoint: /media/external
      media_server: data-vault/media-server
      private: data-vault/private


###### NFS

nfs_network: "{{ home_local_network }}"
nfs_shares:
  system: []
  zfs:
    - "{{ _drives.zfs.data_vault.private }}"
    - "{{ _drives.zfs.data_vault.media_server }}"


###### Samba

samba_user: "{{ ansible_user }}"
samba_password: "{{ vault_samba_password }}"
samba_shares:
  system: []
  zfs:
    - name: "{{ _drives.zfs.data_vault.private }}"
      path: "{{ _drives.zfs.data_vault.mountpoint }}/{{ _drives.zfs.data_vault.private }}"
    - name: "{{ _drives.zfs.data_vault.media_server }}"
      path: "{{ _drives.zfs.data_vault.mountpoint }}/{{ _drives.zfs.data_vault.media_server }}"

### Docker

_docker_base_infra: /opt/docker

###### DIUN

diun_schedule: 0 0 4 * * 6 # Every saturday at 04h00

###### Media Server

media_server_infra: "{{ _docker_base_infra }}/media-server/"
media_server_data: "{{ _drives.zfs.data_vault.mountpoint }}/{{ _drives.zfs.data_vault.media_server }}"
media_server_subnet: 172.31.255.0/24

###### Joplin

joplin_infra: "{{ _docker_base_infra }}/joplin/"
joplin_data: "{{ _drives.zfs.data_vault.mountpoint }}/{{ _drives.zfs.data_vault.private }}/volumes/joplin/data/"

###### Nextcloud

nextcloud_infra: "{{ _docker_base_infra }}/nextcloud/"
nextcloud_data: "{{ _drives.zfs.data_vault.mountpoint }}/{{ _drives.zfs.data_vault.private }}/volumes/nextcloud/data/"

###### Mealie

mealie_infra: "{{ _docker_base_infra }}/mealie/"

###### Caddy

caddy_infra: "{{ _docker_base_infra }}/caddy/"
caddy_caddyfiles_folder: "{{ caddy_infra }}/caddyfiles/"
caddy_subnet: 172.31.251.0/24
