---
### Ansible

username: acer
ip: 192.168.1.202
ssh:
  key: ~/.ssh/acer
  port: 22

ansible_host: "{{ ip }}"
ansible_user: "{{ username }}"
ansible_connection: ssh
ansible_port: "{{ ssh.port }}"
ansible_ssh_private_key_file: "{{ ssh.key }}"

### Hostname

hostname: aspire

### Docker

docker_volumes_path: /ztank/vault/volumes

### Dropbrear

dropbear:
  gateway: 192.168.1.1
  netmask: 255.255.255.0
  ip: 192.168.1.201
  port: 22
  timeout: 300
  authorized_keys:
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEf5Nt/JVAhptEaxDU/5Rdf284QswbVpKOOWFf7o5RAk ickule@opendan"

### Samba

samba:
  private:
    share: /media/root/zprivate
    user: ickule
    password: "{{ vault_samba_password }}"
  public:
    share: /media/root/zpublic

### ZFS

kernel_headers: linux-headers-amd64
