---
### Ansible

ansible_host: 192.168.1.253
ansible_user: acer
ansible_connection: ssh
ansible_port: 22
ansible_ssh_private_key_file: ~/.ssh/servers

### Firmware packages

firmware_packages:
  - firmware-iwlwifi
  - firmware-realtek
  # - bumblebee-nvidia
  # - primus-nvidia
  # - primus-vk-nvidia

### Hostname

hostname: aspire

### Dropbear

dropbear:
  gateway: 192.168.1.254
  netmask: 255.255.255.0
  ip: 192.168.1.252
  port: 22
  timeout: 300
  authorized_keys:
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEf5Nt/JVAhptEaxDU/5Rdf284QswbVpKOOWFf7o5RAk"

### Network Sharing

_drives:
  media_server_data: /media/external/media-server-data


nfs:
  shares:
    - "{{ _drives.media_server_data }}"

samba:
  private:
    - name: media-server-data
      share: "{{ _drives.media_server_data }}"
      user: "{{ ansible_user }}"
      password: "{{ vault_samba_password }}"

### Docker

_docker:
  base_infra: /opt/docker

###### DIUN

diun_schedule: 0 0 4 * * 6 # Every saturday at 04h00

###### Media Server

media_server:
  infra: "{{ _docker.base_infra }}/media-server/"
  data: "{{ _drives.media_server_data }}"
  subnet: 172.31.255.0/24

###### Caddy

caddy:
  infra: "{{ _docker.base_infra }}/caddy/"
  subnet: 172.31.251.0/24
