---
- name: Get render group info
  ansible.builtin.getent:
    database: group
    key: render

- name: Set a variable for render gid
  ansible.builtin.set_fact:
    render_gid: "{{ ansible_facts.getent_group.render[1] }}"

- name: Create docker folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ media_server.infra }}"

- name: Create all docker infrastructure related folders
  ansible.builtin.file:
    path: "{{ media_server.infra }}/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "../templates"
  when: item.state == 'directory'

- name: Copy all docker files
  ansible.builtin.template:
    src: "{{ item.path }}"
    dest: "{{ media_server.infra }}/{{ item.path | replace('.j2', '') }}"
    mode: "0644"
  with_community.general.filetree: "../templates"
  when:
    - item.state == 'file'
    - "'custom-docker-image-updater.timer.j2' not in item.path"
    - "'custom-docker-image-updater.service.j2' not in item.path"
    - "'recyclarr.yml.j2' not in item.path"

- name: Import custom docker image updater tasks
  ansible.builtin.include_tasks: custom-docker-image-updater.yml

- name: Start the media server services
  community.docker.docker_compose_v2:
    build: always
    project_src: "{{ media_server.infra }}"
    pull: always
    remove_orphans: true

- name: Import update recyclarr config tasks
  ansible.builtin.include_tasks: update-recyclarr-config.yml
