---
- name: Check if system is running Archlinux
  ansible.builtin.fail:
    msg: The system is not running Archlinux!
  when: ansible_distribution != "Archlinux"

- name: Create all dotfiles related folders
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: ""
  when: item.state == 'directory'

- name: Symbolic link all dotfiles
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ xdg_config_home }}/{{ item.path }}"
    state: link
    force: true
  with_community.general.filetree: ""
  when: item.state == 'file'
