# {{ ansible_managed }}

# Use the base qbittorrent image
# diun.platform=linux/amd64
FROM lscr.io/linuxserver/qbittorrent:latest

# Install required packages
RUN apk upgrade
RUN apk add --no-cache wireguard-tools iptables

# Expose required ports
EXPOSE {{ media_server_wireguard_port }}/udp
EXPOSE {{ media_server_vault_wireguard_conf.torrenting_port }}
EXPOSE {{ media_server_vault_wireguard_conf.torrenting_port }}/udp

# Install vuetorrent UI
RUN curl -fsSL "https://github.com/vuetorrent/vuetorrent/releases/latest/download/vuetorrent.zip" > "/tmp/vuetorrent.zip"
RUN unzip "/tmp/vuetorrent.zip" -d /
RUN rm "/tmp/vuetorrent.zip"
RUN chmod -R u=rwX,go=rX "/vuetorrent"

# Copy the S6-overlay and WireGuard configuration files
COPY /root /
RUN chmod 600 /etc/wireguard/wg0.conf
RUN chmod 755 /etc/wireguard/*.sh
