---
home:
  children:
    pc:
      hosts:
        opendan:
    servers:
      hosts:
        aspire:

    laptops:
      hosts:
        aspire:
    desktops:
      hosts:
        opendan:
    vm:
    sbc:
