---
- name: Check if system is running Debian
  ansible.builtin.fail:
    msg: The system is not running Debian!
  when: ansible_distribution != "Debian"

- name: Install unattended upgrades packages
  become: true
  ansible.builtin.apt:
    name:
      - unattended-upgrades
    state: present

- name: Copy unattended-upgrades configuration files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    mode: "0644"
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades
