---
- name: Add support for https repos
  become: true
  ansible.builtin.apt:
    name: apt-transport-https

- name: Copy sources.list file
  become: true
  ansible.builtin.template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    mode: "0644"

- name: Update Debian system fully
  become: true
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    autoclean: true
    autoremove: true
  notify: Reboot if required

- name: Check if reboot is needed
  become: true
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: system_reboot_required

- name: Install firmware packages
  become: true
  ansible.builtin.apt:
    name: "{{ firmware_packages }}"
  when: firmware_packages is defined
