---
- name: Import Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_distribution == "Debian"

- name: Import servers tasks
  ansible.builtin.include_tasks: servers.yml
  when: inventory_hostname in groups['servers']

- name: Import Laptops tasks
  ansible.builtin.include_tasks: laptops.yml
  when: inventory_hostname in groups['laptops']

- name: Import Single Board Computer tasks
  ansible.builtin.include_tasks: sbc.yml
  when: inventory_hostname in groups['sbc']

- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  when: inventory_hostname not in groups['vm']

- name: Set timezone
  become: true
  community.general.timezone:
    name: "{{ timezone }}"
  when: inventory_hostname not in groups['vm']

- name: Create all XDG folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ xdg_bin_home }}"
    - "{{ xdg_cache_home }}"
    - "{{ xdg_config_home }}"
    - "{{ xdg_data_home }}"
    - "{{ xdg_state_home }}"

- name: Install core system packages
  become: true
  ansible.builtin.package:
    name: "{{ home_system_packages }}"
    state: present

- name: Allow all handlers to run
  ansible.builtin.meta: flush_handlers
