---
### Ansible

ansible_python_interpreter: auto_silent

### XDG Folders

xdg_config_home: $HOME/.config
xdg_cache_home: $HOME/.cache
xdg_data_home: $HOME/.local/share
xdg_state_home: $HOME/.local/state
xdg_bin_home: $HOME/.local/bin

### Environment variables

home_env_vars:
  - XDG_CONFIG_HOME {{ xdg_config_home }}
  - XDG_CACHE_HOME {{ xdg_cache_home }}
  - XDG_DATA_HOME {{ xdg_data_home }}
  - XDG_STATE_HOME {{ xdg_state_home }}
  - XDG_BIN_HOME {{ xdg_bin_home }}
  - EDITOR nvim
  - PAGER less
  - ANSIBLE_HOME $XDG_DATA_HOME/ansible
  - ANSIBLE_CONFIG $XDG_CONFIG_HOME/ansible.cfg
  - ANSIBLE_GALAXY_CACHE_DIR $XDG_CACHE_HOME/ansible/galaxy_cache

path:
  - $XDG_BIN_HOME

### System

home_system_packages:
  - neovim
  - less
  - curl
  - btop
  - btrfs-progs
  - rsync

timezone: Europe/Paris

local_network: 192.168.1.0/24

debian_package_url: https://deb.debian.org/debian
debian_security_url: https://security.debian.org/debian-security

### MSMTP (chriswayg.msmtp-mailer)

msmtp_accounts:
  - account: custom # Can't be named "default"
    host: "{{ vault_email.smtp.host }}"
    port: "{{ vault_email.smtp.startls }}"
    auth: "on"
    from: "{{ vault_email.from }}"
    user: "{{ vault_email.user }}"
    password: "{{ vault_email.password }}"

msmtp_default_account: custom
msmtp_domain: "{{ vault_base_domain }}"

msmtp_alias_default: "{{ vault_email.from }}"

msmtp_remove_mtas: true

### SSH security (geerlingguy.security)

security_sudoers_passwordless:
  - "{{ ansible_user }}"
security_autoupdate_enabled: false # Handled by a dedicated role

### Autoupdate

autoupdate:
  reboot: false
  mail_to: "{{ vault_email.to }}"
  reboot_time: 04:00
  mail_report: on-change # Could be "always", "on-change" or "only-on-error"
