---
### Environment variables

xdg_config_home: $HOME/.config
xdg_cache_home: $HOME/.cache
xdg_data_home: $HOME/.local/share
xdg_state_home: $HOME/.local/state
xdg_bin_home: $HOME/.local/bin

editor: vim

env_vars:
  global:
    - name: XDG_CONFIG_HOME
      default: "{{ xdg_config_home }}"
      override: '""'
    - name: XDG_CACHE_HOME
      default: "{{ xdg_cache_home }}"
      override: '""'
    - name: XDG_DATA_HOME
      default: "{{ xdg_data_home }}"
      override: '""'
    - name: XDG_STATE_HOME
      default: "{{ xdg_state_home }}"
      override: '""'
    - name: EDITOR
      default: "{{ editor }}"
      override: '""'
  user:
    - PATH {{ xdg_bin_home }} $PATH

### System

system_apps:
  - vim
  - curl

### Fish modules

fish_modules:
  - IlanCosman/tide@v5
  - jorgebucaran/autopair.fish

### System

debian_package_url: https://deb.debian.org/debian
debian_security_url: https://security.debian.org/debian-security
