---
- name: Import Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_distribution == "Debian"

- name: Import Arch Linux tasks
  ansible.builtin.include_tasks: archlinux.yml
  when: ansible_distribution == "Archlinux"

- name: Create all fish related folders
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/fish/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "../templates"
  when: item.state == 'directory'

- name: Copy fish user config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ xdg_config_home }}/fish/{{ item.path | replace('.j2', '') }}"
    mode: "0644"
  with_community.general.filetree: "../templates"
  when: item.state == 'file'

# This task is necessary as VSCode remote is spotty when the target user is using the fish shell as a login shell
- name: Add fish as an interactive shell for servers
  ansible.builtin.blockinfile:
    marker: "# {mark} Use fish interactive shell"
    path: $HOME/.bashrc
    insertafter: EOF
    block: |
      fish
    backup: true
  when: inventory_hostname in groups['servers']

- name: Change the current user shell to fish
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish
  when: inventory_hostname not in groups['servers']

- name: Install fish modules # noqa: no-changed-when Configuring this also updates the modules
  ansible.builtin.shell: fisher install {{ item }}
  args:
    executable: /usr/bin/fish
  with_items: "{{ fish_modules }}"
